# Generated by Django 3.1 on 2020-09-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='avatar',
            field=models.ImageField(blank=True, default='https://gw.alipayobjects.com/zos/rmsportal/mqaQswcyDLcXyDKnZfES.png', null=True, upload_to='avatars/'),
        ),
    ]
