# Generated by Django 3.1 on 2020-09-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/Obiwan.png', null=True, upload_to='avatars/'),
        ),
    ]
